
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[203] =
    {   0,
       29,   29,    0,    0,    0,    0,    0,    0,   65,   63,
       62,    1,    2,    1,   49,    4,   35,   63,   63,   50,
       51,   33,   38,   56,   39,   29,   34,   28,   57,   42,
       46,   43,   27,   27,   54,   55,   27,   27,   27,   27,
       27,   27,   27,   52,   63,   53,   13,   11,   13,   13,
       17,   16,   17,   17,    9,    6,    9,    8,    9,    1,
        2,   45,   47,    0,    0,   61,    0,    3,    0,   36,
       37,   31,   29,   32,   30,   10,   14,   29,   28,   30,
       40,   44,   41,   27,   27,   30,   30,   27,   27,   27,
       27,   27,   18,   27,   27,   27,   27,   27,   48,   11,

       12,   16,   15,    0,    6,    7,    0,    5,    0,    0,
       58,    0,    0,    0,    0,   31,   31,   32,   32,   30,
       30,   29,   30,   29,   30,   29,   30,   30,   30,   27,
       27,   27,   20,   22,   27,   27,   27,   27,    0,    0,
       60,    0,    0,   60,    0,    0,   59,    0,    0,    0,
       59,    0,    0,   59,    0,   31,   31,   31,   29,   30,
       30,   30,   30,   30,   30,   19,   27,   27,   27,   24,
       27,    0,   60,    0,    0,    0,    0,   60,    0,    0,
       60,    0,   30,   23,   27,   27,   21,    0,    0,    0,
        0,    0,    0,    0,   26,   25,    0,   60,    0,    0,

        0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        5,    5,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    7,    8,    1,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,    1,   31,    1,   32,   33,   26,   34,

       35,   36,   26,   37,   38,   26,   26,   39,   26,   40,
       41,   42,   26,   43,   44,   45,   46,   47,   48,   26,
       26,   26,   49,   50,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    1,    4,
        4,    1,    1,    1,    1,    4,    4,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[215] =
    {   0,
        0,    0,   48,   49,   52,   53,   60,   61,  329,  747,
      747,   67,  747,   71,  288,  747,  747,  289,   89,  747,
      747,  747,  280,  747,  256,   78,   64,   88,  747,  238,
      229,  223,   40,   99,  747,  747,  198,   83,   91,   59,
       66,  108,  115,  747,  184,  747,  747,  747,  226,  198,
      747,  747,  180,  126,  747,  747,  154,  747,  149,  134,
      747,  747,  747,  137,  150,  747,  159,  747,  193,  747,
      747,  124,  156,   64,  185,  747,  747,    0,    0,  224,
      747,  747,  747,  126,  147,  189,  228,  147,  237,  151,
      194,  207,  166,  198,  240,  211,  244,  246,  747,  747,

      747,  747,  747,  146,  747,  747,  134,  747,  169,  264,
      747,  290,  268,  277,  334,  282,  326,  256,  265,  293,
      330,  206,  363,  254,  370,  368,  379,  384,  389,  400,
      269,  295,  271,  287,  335,  352,  348,  392,  419,  422,
      747,  444,  428,   81,    0,  431,  747,  484,   96,  276,
      747,  524,  432,  179,    0,  447,  451,  476,  480,  519,
      531,  541,  429,  557,  564,  304,  438,  485,  420,  311,
      488,  544,  182,    0,  307,  578,  559,  576,  104,  586,
      590,  441,  607,  338,  372,  498,  433,  310,    0,  621,
      591,  661,    0,    0,  501,  505,  602,  629,   92,  633,

      587,  747,  708,  712,  716,  720,  722,   84,  726,   67,
      730,  734,  738,  742
    } ;

static const flex_int16_t yy_def[215] =
    {   0,
      202,    1,  203,  203,  204,  204,  205,  205,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  206,  202,
      202,  202,  202,  202,  202,  207,  202,  207,  202,  202,
      202,  202,  208,  208,  202,  202,   34,  208,  208,  208,
      208,  208,  208,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  209,  209,  202,  209,  202,  209,  202,
      202,  202,  207,  210,  210,  202,  202,   73,   28,  210,
      202,  202,  202,  208,  208,  202,  202,   34,   34,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  211,  211,
      202,  211,  212,  213,  212,  202,  202,  210,  210,  202,
      202,   75,   75,   80,   80,   28,  202,  202,  202,   34,
      208,  208,  208,  208,  208,  208,  208,  208,  211,  211,
      202,  112,  211,  214,  142,  211,  202,  142,  214,  214,
      202,  214,  211,  214,  148,  202,  202,  202,   28,  202,
      202,  202,   75,   80,   80,  208,  208,  208,  208,  208,
      208,  211,  214,  142,  214,  214,  211,  214,  142,  214,
      214,  176,   75,  208,  208,  208,  208,  214,  176,  142,
      214,  214,  190,  192,  208,  208,  211,  214,  142,  214,

      176,    0,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202
    } ;

static const flex_int16_t yy_nxt[799] =
    {   0,
       10,   11,   12,   13,   12,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       28,   29,   30,   31,   32,   33,   34,   35,   10,   36,
       33,   33,   33,   33,   37,   38,   33,   39,   33,   33,
       33,   40,   41,   33,   33,   33,   42,   43,   44,   45,
       46,   48,   48,   49,   49,   52,   52,   53,   53,   84,
       84,   50,   50,   56,   56,   57,   57,   58,   58,   60,
      119,   60,   60,   60,   61,   60,   60,   76,   84,   84,
       54,   54,   77,  118,  118,   84,   84,   85,   59,   59,
       65,  141,   66,   65,   67,   72,   65,   73,   73,   68,

       96,   95,   84,   84,   75,   78,  141,   79,   79,  176,
       84,   84,   75,   86,   80,   86,   87,   69,   88,   88,
      193,   91,   80,   92,  176,   89,   93,   84,   84,  103,
       94,  104,  193,   89,   84,   84,   60,  106,   60,   60,
       66,   72,  110,  116,  116,   84,   84,  111,   97,  103,
      117,   98,  106,   66,  107,  110,  108,  105,  117,  108,
      202,  202,   66,  202,  110,  112,   84,   84,  108,  202,
       84,   84,   66,   72,  140,   73,   73,  108,  112,  141,
      108,  108,   75,  102,  108,   84,   84,  112,  108,  141,
       75,  108,  141,  108,  131,  108,   66,  142,  110,  120,

      113,  120,  121,  114,  122,  122,   87,  176,  126,  126,
      176,  123,  113,   84,   84,  127,  101,   84,   84,  123,
      202,  115,  202,  127,  113,  113,   84,   84,  113,  100,
       84,   84,  113,   99,  132,  113,   90,  113,   86,  113,
       86,   87,  134,  124,  124,   87,   83,  128,  128,  133,
      125,  129,   82,  129,  127,  136,  130,  130,  125,   84,
       84,   81,  127,   84,   84,   84,   84,   66,  202,  140,
      202,   66,   71,  146,  141,  118,  118,  135,  147,   66,
       66,  137,  150,  138,  118,  118,  141,  151,   84,   84,
       84,   84,  142,   66,   70,  140,  148,  143,   63,   72,

      144,  116,  116,  166,  176,  152,   84,   84,  117,  143,
      121,   62,  159,  159,   84,   84,  117,  141,  145,  160,
      141,  143,  143,   84,   84,  143,  167,  160,  202,  143,
       84,   84,  143,  202,  143,  176,  143,   66,  176,  146,
      156,  153,  156,  157,  154,  158,  158,  121,  202,  161,
      161,  202,  117,  153,   84,   84,  160,   84,   84,  202,
      117,  202,  155,  202,  160,  153,  153,   84,   84,  153,
      202,   84,   84,  153,  168,  202,  153,  162,  153,  162,
      153,  170,  163,  163,  129,   87,  129,  126,  126,  164,
      164,   84,   84,  129,  165,  129,   87,  169,  128,  128,

      202,   87,  165,  128,  128,  127,   87,  195,  128,  128,
      127,   84,   84,  127,  202,  127,  202,  202,  127,  130,
      130,  202,   66,  127,  140,   66,  202,  140,  202,  141,
      171,   66,  141,  140,   66,   66,  140,  140,  141,   84,
       84,  141,  141,  202,   66,  202,  191,  142,  163,  163,
      142,  172,   84,   84,  173,  202,  142,   84,   84,  142,
      142,  202,  186,  172,  157,  202,  158,  158,  157,  194,
      158,  158,  174,  117,  202,  172,  172,  117,  202,  172,
      202,  117,  184,  172,  202,  117,  172,  202,  172,  202,
      172,  177,  202,  157,  178,  158,  158,  121,  202,  159,

      159,  202,  117,  177,   84,   84,  183,   84,   84,  202,
      117,  202,  179,  202,  183,  177,  177,   84,   84,  177,
       84,   84,  187,  177,   84,   84,  177,  202,  177,  185,
      177,  180,  202,  162,  181,  162,  121,  196,  161,  161,
      202,  202,  202,  180,  202,  160,  202,   66,  121,  140,
      161,  161,  182,  160,  141,  180,  180,  160,  121,  180,
      161,  161,   66,  180,  140,  160,  180,  160,  180,  141,
      180,  202,  142,  202,  202,  160,  164,  164,  129,   66,
      129,  191,  202,  164,  164,  188,  141,  190,  173,   66,
       66,  191,  191,   66,   66,  191,  141,  188,  202,  202,

      141,  141,  202,  202,  192,   66,  189,  140,  202,  188,
      188,  202,  141,  188,  192,  194,  202,  188,  192,  176,
      188,  162,  188,  162,  188,  202,  163,  163,  197,  202,
      190,  198,   66,  202,  191,  202,   66,  202,  191,  141,
      197,  202,  202,  141,  202,  202,  202,  202,  202,  199,
      202,  202,  197,  197,  202,  202,  197,  192,  202,  202,
      197,  192,  202,  197,  202,  197,  202,  197,  200,  202,
      202,  198,  202,  202,  202,  202,  202,  202,  202,  202,
      200,  202,  202,  202,  202,  202,  202,  202,  202,  201,
      202,  202,  200,  200,  202,  202,  200,  202,  202,  202,

      200,  202,  202,  200,  202,  200,  202,  200,   47,   47,
       47,   47,   51,   51,   51,   51,   55,   55,   55,   55,
       64,   64,   64,   64,   74,   74,  109,  109,  109,  109,
      139,  139,  139,  139,  143,  143,  143,  143,  149,  149,
      149,  149,  175,  202,  175,  175,    9,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202

    } ;

static const flex_int16_t yy_chk[799] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,    5,    6,    5,    6,   33,
       33,    3,    4,    7,    8,    7,    8,    7,    8,   12,
      210,   12,   12,   14,   14,   14,   14,   27,   40,   40,
        5,    6,   27,   74,   74,   41,   41,  208,    7,    8,
       19,  144,   19,   19,   19,   26,   19,   26,   26,   19,

       41,   40,   38,   38,   26,   28,  149,   28,   28,  144,
       39,   39,   26,   34,   28,   34,   34,   19,   34,   34,
      199,   38,   28,   38,  149,   34,   39,   42,   42,   54,
       39,   54,  179,   34,   43,   43,   60,  107,   60,   60,
       64,   72,   64,   72,   72,   84,   84,   64,   42,  104,
       72,   43,   59,   65,   59,   65,   59,   57,   72,   59,
       65,   88,   67,   88,   67,   64,   85,   85,   59,   67,
       90,   90,  109,   73,  109,   73,   73,   59,   65,  109,
       59,   59,   73,   53,   59,   93,   93,   67,   59,  154,
       73,   59,  173,   59,   90,   59,   69,  109,   69,   75,

       69,   75,   75,   69,   75,   75,   86,  154,   86,   86,
      173,   75,   69,   91,   91,   86,   50,   94,   94,   75,
      122,   69,  122,   86,   69,   69,   92,   92,   69,   49,
       96,   96,   69,   45,   91,   69,   37,   69,   80,   69,
       80,   80,   94,   80,   80,   87,   32,   87,   87,   92,
       80,   89,   31,   89,   87,   96,   89,   89,   80,   95,
       95,   30,   87,   97,   97,   98,   98,  110,  124,  110,
      124,  113,   25,  113,  110,  118,  118,   95,  113,  150,
      114,   97,  114,   98,  119,  119,  150,  114,  131,  131,
      133,  133,  110,  112,   23,  112,  113,  112,   18,  116,

      112,  116,  116,  131,  150,  114,  134,  134,  116,  112,
      120,   15,  120,  120,  132,  132,  116,  175,  112,  120,
      188,  112,  112,  166,  166,  112,  132,  120,    9,  112,
      170,  170,  112,    0,  112,  175,  112,  115,  188,  115,
      117,  115,  117,  117,  115,  117,  117,  121,    0,  121,
      121,    0,  117,  115,  135,  135,  121,  184,  184,    0,
      117,    0,  115,    0,  121,  115,  115,  137,  137,  115,
        0,  136,  136,  115,  135,    0,  115,  123,  115,  123,
      115,  137,  123,  123,  125,  126,  125,  126,  126,  125,
      125,  185,  185,  127,  126,  127,  127,  136,  127,  127,

        0,  128,  126,  128,  128,  127,  129,  185,  129,  129,
      128,  138,  138,  127,  130,  129,  130,    0,  128,  130,
      130,    0,  139,  129,  139,  140,    0,  140,    0,  139,
      138,  143,  140,  143,  146,  153,  146,  153,  143,  169,
      169,  146,  153,  163,  182,  163,  182,  139,  163,  163,
      140,  142,  187,  187,  142,    0,  143,  167,  167,  146,
      153,    0,  169,  142,  156,    0,  156,  156,  157,  182,
      157,  157,  142,  156,    0,  142,  142,  157,    0,  142,
        0,  156,  167,  142,    0,  157,  142,    0,  142,    0,
      142,  148,    0,  158,  148,  158,  158,  159,    0,  159,

      159,    0,  158,  148,  168,  168,  159,  171,  171,    0,
      158,    0,  148,    0,  159,  148,  148,  186,  186,  148,
      195,  195,  171,  148,  196,  196,  148,    0,  148,  168,
      148,  152,    0,  160,  152,  160,  160,  186,  160,  160,
        0,    0,    0,  152,    0,  160,    0,  172,  161,  172,
      161,  161,  152,  160,  172,  152,  152,  161,  162,  152,
      162,  162,  177,  152,  177,  161,  152,  162,  152,  177,
      152,  164,  172,  164,    0,  162,  164,  164,  165,  178,
      165,  178,    0,  165,  165,  176,  178,  177,  176,  180,
      201,  180,  201,  181,  191,  181,  180,  176,    0,    0,

      181,  191,    0,    0,  178,  197,  176,  197,    0,  176,
      176,    0,  197,  176,  180,  201,    0,  176,  181,  191,
      176,  183,  176,  183,  176,    0,  183,  183,  190,    0,
      197,  190,  198,    0,  198,    0,  200,    0,  200,  198,
      190,    0,    0,  200,    0,    0,    0,    0,    0,  190,
        0,    0,  190,  190,    0,    0,  190,  198,    0,    0,
      190,  200,    0,  190,    0,  190,    0,  190,  192,    0,
        0,  192,    0,    0,    0,    0,    0,    0,    0,    0,
      192,    0,    0,    0,    0,    0,    0,    0,    0,  192,
        0,    0,  192,  192,    0,    0,  192,    0,    0,    0,

      192,    0,    0,  192,    0,  192,    0,  192,  203,  203,
      203,  203,  204,  204,  204,  204,  205,  205,  205,  205,
      206,  206,  206,  206,  207,  207,  209,  209,  209,  209,
      211,  211,  211,  211,  212,  212,  212,  212,  213,  213,
      213,  213,  214,    0,  214,  214,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1705067.l"



#line 10 "1705067.l"
#include<bits/stdc++.h>
#include "1705067_ST.cpp"
#include "y.tab.h"
using namespace std;

extern YYSTYPE yylval;
extern SymbolTable *table;
extern ofstream logout;
extern ofstream errorfile;
extern int line_count;
extern int error_calc;
void yyerror(char *);


int error_count = 0;
int error_line;



#line 714 "lex.yy.c"
#line 715 "lex.yy.c"

#define INITIAL 0
#define MULTILINESTATE 1
#define SINGLELINE 2
#define STRINGSTATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 47 "1705067.l"


#line 938 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 203 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 747 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "1705067.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 51 "1705067.l"
{line_count++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "1705067.l"
{
			/*
			logout<<"Error at line no "<< line_count<< ": Empty character constant error "<< yytext<<endl;
			logout<<endl;
			error_count++;
			*/
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "1705067.l"
{
		/*
		str1 = yytext;
		str2 = yytext;
		error_line = line_count;
		BEGIN STRINGSTATE;
		*/
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 72 "1705067.l"
{
			/*
			char c;
			string str;
			str = yytext;
			if(str.compare("\\t")==0)
				 c = '\t';
			else if(str.compare("\\n")==0)
				 c = '\n';
			else if(str.compare("\\a")==0)
				 c = '\a';
			else if(str.compare("\\f")==0)
				 c = '\f';
			else if(str.compare("\\r")==0)
				 c = '\r';
			else if(str.compare("\\b")==0)
				 c = '\b';
			else if(str.compare("\\v")==0)
				 c = '\v';
			else if(str.compare("\\0")==0)
				 c = '\n';
			else if(str.compare("\\\\")==0)
				 c = '\\';
			else if(str.compare("\\\'")==0)
				 c = '\'';
			else if(str.compare("\\\"")==0)
				 c = '\"';
			str1 = str1 + c;
			str2 = str2 + yytext; 
			*/
		}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 104 "1705067.l"
{ 
		/*
		line_count++;
		logout<<"Error at line no "<< error_line << ": Unterminated String "<< str2 <<endl;
		logout<<endl;
		error_count++;
		BEGIN INITIAL;
		*/
		
	}
	YY_BREAK
case YY_STATE_EOF(STRINGSTATE):
#line 114 "1705067.l"
{ 
		/*
		logout<<"Error at line no "<< error_line << ": Unterminated String "<< str2 <<endl;
		logout<<endl;
		error_count++;
		BEGIN INITIAL;
		*/
		
	}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 124 "1705067.l"
{ 
		/*
		line_count++;
		str2 = str2 + yytext;
		*/
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 132 "1705067.l"
{ 
		/*
		str1 = str1 + yytext;
		str2 = str2 + yytext;
		tokenout<<"<STRING, "<<str1<<"> ";
		logout<<"Line no "<< error_line <<": Token <STRING> Lexeme "<< str2<<" found"<<" --> <STRING, "<<str1<<"> "<<endl;
		logout<<endl;
		BEGIN INITIAL;
		*/
			
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 143 "1705067.l"
{ 
		/*
		str1 = str1 + yytext;
		str2 = str2 + yytext;
		*/
	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 150 "1705067.l"
{	
		/*
		str3 = yytext;
		error_line = line_count;
		BEGIN MULTILINESTATE;
		*/
	}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 159 "1705067.l"
{
		/*
		str3 = str3 + yytext;
		line_count++;
		*/
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 166 "1705067.l"
{
		/*
		str3 = str3 + yytext;
		logout<<"Line no "<< error_line <<": Token <COMMENT> Lexeme "<< str3<<" found"<<endl;
		logout<<endl;
		BEGIN INITIAL;
		*/
	}
	YY_BREAK
case YY_STATE_EOF(MULTILINESTATE):
#line 175 "1705067.l"
{
		/*
		logout<<"Error at line no "<< error_line << ": Unterminated Comment "<< str3 <<endl;
		logout<<endl;
		error_count++;
		BEGIN INITIAL;
		*/
		}	
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 184 "1705067.l"
{
		//str3 = str3 + yytext;
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 188 "1705067.l"
{
			
	//	logout<<"Line no "<< line_count<< ": Token <COMMENT> Lexeme ";
	//	logout<<yytext;
		BEGIN SINGLELINE;
		
	}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 197 "1705067.l"
{
			
		//	logout<<yytext;
			line_count++;
			BEGIN SINGLELINE;
			
		}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 205 "1705067.l"
{
				
		//	logout<<" found"<<endl;
		//	logout<<endl;
			line_count++;
			BEGIN INITIAL;
			
		}
	YY_BREAK
case YY_STATE_EOF(SINGLELINE):
#line 214 "1705067.l"
{
				
		//	logout<<" found"<<endl;
		//	logout<<endl;
			BEGIN INITIAL;
			
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 222 "1705067.l"
{
			//logout<<yytext;
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 227 "1705067.l"
{	
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("IF");
			yylval.si = s;
			return IF;
			
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 236 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("ELSE");
			yylval.si = s;
			return ELSE;	
		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 243 "1705067.l"
{	
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("FOR");
			yylval.si = s;
			return FOR;
			
		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 252 "1705067.l"
{
		 	SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("WHILE");
			yylval.si = s;
			return WHILE;	
		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 260 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("INT");
			yylval.si = s;
			return INT;
		}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 268 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("FLOAT");
			yylval.si = s;
			return FLOAT;
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 276 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("VOID");
			yylval.si = s;
			return VOID;
		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 283 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("RETURN");
			yylval.si = s;
			return RETURN;
		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 291 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("PRINTLN");
			yylval.si = s;
			return PRINTLN;
		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 298 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("ID");
			yylval.si = s;
			return ID;
			
		}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 307 "1705067.l"
{		
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("CONST_INT");
			yylval.si = s;
			return CONST_INT;	
		}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 315 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("CONST_FLOAT");
			yylval.si = s;
			return CONST_FLOAT;

		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 324 "1705067.l"
{
			/*
			logout<<"Error at line no "<< line_count<< ": Ill formed number "<< yytext<<endl;
			logout<<endl;
			error_count++;
			*/
	
 		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 333 "1705067.l"
{
			/*
			logout<<"Error at line no "<< line_count<< ": Too many decimal points "<< yytext<<endl;
			logout<<endl;
			error_count++;
			*/

                }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 343 "1705067.l"
{
			/*
			logout<<"Error at line no "<< line_count<< ": Invalid prefix on ID or invalid suffix on Number "<< yytext<<endl;
			logout<<endl;
			error_count++;
			*/
		}		
	YY_BREAK
case 33:
#line 353 "1705067.l"
case 34:
#line 354 "1705067.l"
case 35:
YY_RULE_SETUP
#line 355 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("MULOP");
			yylval.si = s;
			return MULOP;
		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 362 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("INCOP");
			yylval.si = s;
			return INCOP;
		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 370 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("DECOP");
			yylval.si = s;
			return DECOP;
		}
	YY_BREAK
case 38:
#line 378 "1705067.l"
case 39:
YY_RULE_SETUP
#line 379 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("ADDOP");
			yylval.si = s;
			return ADDOP;
		} 
	YY_BREAK
case 40:
#line 390 "1705067.l"
case 41:
#line 391 "1705067.l"
case 42:
#line 392 "1705067.l"
case 43:
#line 393 "1705067.l"
case 44:
#line 394 "1705067.l"
case 45:
YY_RULE_SETUP
#line 394 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("RELOP");
			yylval.si = s;
			return RELOP;
		} 		
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 402 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("ASSIGNOP");
			yylval.si = s;
			return ASSIGNOP;
		} 
	YY_BREAK
case 47:
#line 411 "1705067.l"
case 48:
YY_RULE_SETUP
#line 411 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("LOGICOP");
			yylval.si = s;
			return LOGICOP;
		} 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 419 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("NOT");
			yylval.si = s;
			return NOT;
		} 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 427 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("LPAREN");
			yylval.si = s;
			return LPAREN;
		} 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 435 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("RPAREN");
			yylval.si = s;
			return RPAREN;
		} 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 443 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("LCURL");
			yylval.si = s;
			return LCURL;
			
		} 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 452 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("RCURL");
			yylval.si = s;
			return RCURL;
		} 
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 460 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("LTHIRD");
			yylval.si = s;
			return LTHIRD;
		}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 468 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("RTHIRD");
			yylval.si = s;
			return RTHIRD;
		} 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 476 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("COMMA");
			yylval.si = s;
			return COMMA;
		} 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 484 "1705067.l"
{
			SymbolInfo *s = new SymbolInfo();
			s->setName(yytext);
        		s->setType("SEMICOLON");
			yylval.si = s;
			return SEMICOLON;
		} 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 494 "1705067.l"
{
			/*
			tokenout<<"<CONST_CHAR, "<<yytext[1]<<"> ";
			logout<<"Line no "<< line_count<< ": Token <CONST_CHAR> Lexeme "<< yytext<<" found"<<" --> <CONST_CHAR, "<<yytext[1]<<"> "<<endl;
			logout<<endl;
			t = sb.insert(yytext,"CONST_CHAR");
			if(t)
				sb.PrintAll();
			*/
		}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 506 "1705067.l"
{
			/*
			char c;
			string str;
			str = yytext;
			if(str.compare("\'\\t\'")==0)
				 c = '\t';
			else if(str.compare("\'\\n\'")==0)
				 c = '\n';
			else if(str.compare("\'\\a\'")==0)
				 c = '\a';
			else if(str.compare("\'\\f\'")==0)
				 c = '\f';
			else if(str.compare("\'\\r\'")==0)
				 c = '\r';
			else if(str.compare("\'\\b\'")==0)
				 c = '\b';
			else if(str.compare("\'\\v\'")==0)
				 c = '\v';
			else if(str.compare("\'\\0\'")==0)
				 c = '\n';
			else if(str.compare("\'\\\\\'")==0)
				 c = '\\';
			else if(str.compare("\'\\\'\'")==0)
				 c = '\'';
			else if(str.compare("\'\\\"\'")==0)
				 c = '\"';	
			tokenout<<"<CONST_CHAR, "<<c<<"> ";
			logout<<"Line no "<< line_count<< ": Token <CONST_CHAR> Lexeme "<< yytext<<" found"<<" --> <CONST_CHAR, "<<c<<"> "<<endl;;
			logout<<endl;
			t = sb.insert(yytext,"CONST_CHAR");
			if(t)
				sb.PrintAll();		
			*/
		}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 543 "1705067.l"
{
			/*
			logout<<"Error at line no "<< line_count<< ": Multi character constant error "<< yytext<<endl;
			logout<<endl;
			error_count++;
			*/
		}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 550 "1705067.l"
{
			/*
			logout<<"Error at line no "<< line_count<< ": Unterminated character "<< yytext<<endl;
			line_count++;
			error_count++;
			*/
		}		
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 558 "1705067.l"
{}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 560 "1705067.l"
{       /*
		logout<<"Error at line no "<< line_count<< ": Unrecognized character "<< yytext<<endl;
		logout<<endl;
		error_count++;
		*/
	}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 568 "1705067.l"
{ 
		
		return 0;
	}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 574 "1705067.l"
ECHO;
	YY_BREAK
#line 1701 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 203 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 203 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 202);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 574 "1705067.l"



